# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qmtl/dag.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qmtl import nodes_pb2 as qmtl_dot_nodes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eqmtl/dag.proto\x12\x04qmtl\x1a\x10qmtl/nodes.proto\")\n\x07\x44\x41GEdge\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\"B\n\x03\x44\x41G\x12\x1d\n\x05nodes\x18\x01 \x03(\x0b\x32\x0e.qmtl.DataNode\x12\x1c\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\r.qmtl.DAGEdgeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qmtl.dag_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DAGEDGE._serialized_start=42
  _DAGEDGE._serialized_end=83
  _DAG._serialized_start=85
  _DAG._serialized_end=151
# @@protoc_insertion_point(module_scope)
