# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qmtl/events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11qmtl/events.proto\x12\x04qmtl\"j\n\x0fNodeStatusEvent\x12#\n\nevent_type\x18\x01 \x01(\x0e\x32\x0f.qmtl.EventType\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"r\n\x13PipelineStatusEvent\x12#\n\nevent_type\x18\x01 \x01(\x0e\x32\x0f.qmtl.EventType\x12\x13\n\x0bpipeline_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"w\n\nAlertEvent\x12#\n\nevent_type\x18\x01 \x01(\x0e\x32\x0f.qmtl.EventType\x12\x11\n\ttarget_id\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t*<\n\tEventType\x12\x0f\n\x0bNODE_STATUS\x10\x00\x12\x13\n\x0fPIPELINE_STATUS\x10\x01\x12\t\n\x05\x41LERT\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qmtl.events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVENTTYPE._serialized_start=372
  _EVENTTYPE._serialized_end=432
  _NODESTATUSEVENT._serialized_start=27
  _NODESTATUSEVENT._serialized_end=133
  _PIPELINESTATUSEVENT._serialized_start=135
  _PIPELINESTATUSEVENT._serialized_end=249
  _ALERTEVENT._serialized_start=251
  _ALERTEVENT._serialized_end=370
# @@protoc_insertion_point(module_scope)
