# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qmtl/nodes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10qmtl/nodes.proto\x12\x04qmtl\".\n\x08NodeTags\x12\x12\n\npredefined\x18\x01 \x03(\t\x12\x0e\n\x06\x63ustom\x18\x02 \x03(\t\"I\n\x10IntervalSettings\x12\x10\n\x08interval\x18\x01 \x01(\t\x12\x0e\n\x06period\x18\x02 \x01(\x05\x12\x13\n\x0bmax_history\x18\x03 \x01(\x05\"\x9a\x01\n\x12NodeStreamSettings\x12:\n\tintervals\x18\x01 \x03(\x0b\x32\'.qmtl.NodeStreamSettings.IntervalsEntry\x1aH\n\x0eIntervalsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.qmtl.IntervalSettings:\x02\x38\x01\"\xf0\x02\n\x08\x44\x61taNode\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x1c\n\x04type\x18\x02 \x01(\x0e\x32\x0e.qmtl.NodeType\x12\x33\n\x0b\x64\x61ta_format\x18\x03 \x03(\x0b\x32\x1e.qmtl.DataNode.DataFormatEntry\x12*\n\x06params\x18\x04 \x03(\x0b\x32\x1a.qmtl.DataNode.ParamsEntry\x12\x14\n\x0c\x64\x65pendencies\x18\x05 \x03(\t\x12\x0b\n\x03ttl\x18\x06 \x01(\x05\x12\x1c\n\x04tags\x18\x07 \x01(\x0b\x32\x0e.qmtl.NodeTags\x12\x31\n\x0fstream_settings\x18\x08 \x01(\x0b\x32\x18.qmtl.NodeStreamSettings\x1a\x31\n\x0f\x44\x61taFormatEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xa5\x01\n\x08NodeType\x12\x07\n\x03RAW\x10\x00\x12\n\n\x06\x43\x41NDLE\x10\x01\x12\x0b\n\x07\x46\x45\x41TURE\x10\x02\x12\r\n\tORDERBOOK\x10\x03\x12\x08\n\x04RISK\x10\x04\x12\n\n\x06SIGNAL\x10\x05\x12\x0b\n\x07ML_PRED\x10\x06\x12\x0c\n\x08\x41NALYZER\x10\x07\x12\x0f\n\x0b\x43ORRELATION\x10\x08\x12\x0e\n\nVOLATILITY\x10\t\x12\t\n\x05TREND\x10\n\x12\x0b\n\x07\x41NOMALY\x10\x0b\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qmtl.nodes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NODESTREAMSETTINGS_INTERVALSENTRY._options = None
  _NODESTREAMSETTINGS_INTERVALSENTRY._serialized_options = b'8\001'
  _DATANODE_DATAFORMATENTRY._options = None
  _DATANODE_DATAFORMATENTRY._serialized_options = b'8\001'
  _DATANODE_PARAMSENTRY._options = None
  _DATANODE_PARAMSENTRY._serialized_options = b'8\001'
  _NODETYPE._serialized_start=678
  _NODETYPE._serialized_end=843
  _NODETAGS._serialized_start=26
  _NODETAGS._serialized_end=72
  _INTERVALSETTINGS._serialized_start=74
  _INTERVALSETTINGS._serialized_end=147
  _NODESTREAMSETTINGS._serialized_start=150
  _NODESTREAMSETTINGS._serialized_end=304
  _NODESTREAMSETTINGS_INTERVALSENTRY._serialized_start=232
  _NODESTREAMSETTINGS_INTERVALSENTRY._serialized_end=304
  _DATANODE._serialized_start=307
  _DATANODE._serialized_end=675
  _DATANODE_DATAFORMATENTRY._serialized_start=579
  _DATANODE_DATAFORMATENTRY._serialized_end=628
  _DATANODE_PARAMSENTRY._serialized_start=630
  _DATANODE_PARAMSENTRY._serialized_end=675
# @@protoc_insertion_point(module_scope)
