# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qmtl/work.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fqmtl/work.proto\x12\x04qmtl\"g\n\x08WorkItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1c\n\x04type\x18\x02 \x01(\x0e\x32\x0e.qmtl.WorkType\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12 \n\x06status\x18\x04 \x01(\x0e\x32\x10.qmtl.WorkStatus*-\n\x08WorkType\x12\x16\n\x12STRATEGY_EXECUTION\x10\x00\x12\t\n\x05OTHER\x10\x01*A\n\nWorkStatus\x12\x0b\n\x07PENDING\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qmtl.work_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORKTYPE._serialized_start=130
  _WORKTYPE._serialized_end=175
  _WORKSTATUS._serialized_start=177
  _WORKSTATUS._serialized_end=242
  _WORKITEM._serialized_start=25
  _WORKITEM._serialized_end=128
# @@protoc_insertion_point(module_scope)
